# Generated by Django 2.2.5 on 2019-09-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal')], db_index=True, default='internal', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal'), ('inherit', 'Inherit')], db_index=True, default='inherit', max_length=32, verbose_name='Status'),
        ),
    ]
